= GR8 CRM - Apache Shiro Security Plugin
Göran Ehrsson <goran@technipelago.se>
:toc:
:numbered:
:icons: font
:imagesdir: ./images
:source-highlighter: prettify
:homepage: http://gr8crm.github.io
:gr8crm: GR8 CRM
:gr8source: https://github.com/goeh/grails-crm-security-shiro
:license: This plugin is licensed with http://www.apache.org/licenses/LICENSE-2.0.html[Apache License version 2.0]

== Introduction

{gr8crm} is a set of http://www.grails.org/[Grails Web Application Framework]
plugins that makes it easy to develop web applications with CRM functionality.

=== Customer relationship management

Customer relationship management (CRM) is a system for managing a company’s interactions with current and future customers.
It involves using technology to organize, automate and synchronize sales, marketing, customer service, and technical support.
http://en.wikipedia.org/wiki/Customer_relationship_management[Wikipedia]

The {gr8crm} "Ecosystem" currently contains over 40 Grails plugins. For a complete list of plugins see http://gr8crm.github.io.

Each {gr8crm} plugin defines a http://martinfowler.com/bliki/BoundedContext.html[Bounded Context]
that focus on one specific domain, for example *contact*, *project* or *document*.

== Apache Shiro Security Plugin

The +crm-security-shiro+ plugin is a sub-plugin to +crm-security+. It implements application security using the Apache Shiro web security framework.

This plugin adds one domain class to the application. +ShiroCrmUser+ contains the username and hashed/salted password for each application user.

== AuthController

This controller have +login()+ and +logout()+ actions that are called when users login and logout of the application.

== ShiroDbRealm

This realm is used when a user tries to login to the application. The database is queried for the user and password is checked.

== Configuration

No configuration needed for this plugin.

== License

{license}

== Source Code

The source code for this plugin is available at {gr8source}
